language: generic

sudo: false

addons:
  apt:
    sources:
    - ubuntu-elisp
    packages:
    - emacs-snapshot

env:
  matrix:
    - EMACS=emacs24

script: emacs --load "./init.el" --script test.el
